interface IAPIInfo {
  uri: string;
  methods: string[];
  middlewares: string[];
  controller: string;
  controller_full_path: string;
  method: string;
  httpMethod: string;
  rules: IAPIRule;
  docBlock: string;
}

interface IAPIRule {
  [key: string]: string[];
}

interface IKeyValueParams {
  key: string;
  value: string;
  disabled?: boolean;
  deleted?: boolean;
}

interface IAPISettings {
  headers: IAPIHeaderSettings;
  params: IAPIParamSettings;
  body: IAPIBodySettings;
}

interface IAPIRequestData {
  headers: IKeyValueParams[];
  params: IKeyValueParams[];
  body: IKeyValueParams[] | Object;
}

interface IAPISettingLocalStorage {
  [key: string]: {
    lrdSettings: IAPISettings;
    lrdData: IAPIRequestData;
  };
}

interface IAPIHeaderSettings {
  keyValue: boolean;
  /**
   * Show auto generated headers
   */
  autoGenerated: boolean;
  /**
   * Show common headers
   */
  common: boolean;
}

interface IAPIParamSettings {
  keyValue: boolean;
}

interface IAPIBodySettings {
  /**
   * application/x-www-form-urlencoded
   * multipart/form-data
   * application/json
   * text/plain
   * application/xml
   */
  contentType: string;
  /**
   * only apply for form-data and x-www-form-urlencoded
   */
  keyValue: boolean; 
}

const sampleJSON = {
  "POST_api/v1/health": {
    "lrdSettings": {
      "headers": {
        "keyValue": "true",
        "autoGenerated": "true",
        "common": "true",
      },
      "params": {
        "keyValue": "true",
      },
      "body": {
        "contentType": "application/json",
        "keyValue": "true", // only apply for form-data and x-www-form-urlencoded
      },
    },
    "lrdData": {
      "headers": [],
      "params": [],
      "body": [],
    },
  }
}