on:
  - push

name: "CI PHP test"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: ['8.*', '11.*']
        include:
          - php: 8.0
            laravel: 9.*
          - php: 8.1
            laravel: 9.*
          - php: 8.2
            laravel: 9.*
          - php: 8.1
            laravel: 10.*
          - php: 8.2
            laravel: 10.*
          - php: 8.3
            laravel: 10.*
          - php: '8.2'
            laravel: 11.*
        exclude:
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: intl, gd, zip, pdo, sqlite, pdo_sqlite, dom, curl, libxml, mbstring, fileinfo, exif, iconv
          ini-values: memory_limit=-1,disable_functions="",pcov.exclude="~(vendor|tests|node_modules)~",pcov.directory="./"
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Composer Install
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer install

      - name: PHPUNIT Tests
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          name: PHP ${{ matrix.php }}
          files: coverage.xml
